#!/bin/bash

usage() {
  echo "Usage: $0 [-f]"
  echo "  -f    Force overwrite if the output file already exists"
  echo "  -h    Show this help message"
}

FORCE=0

# Parse options
while getopts "fh" opt; do
  case "$opt" in
    f) FORCE=1 ;;
    h) usage; exit 0 ;;
    *) usage; exit 1 ;;
  esac
done

# Get monitors from hyprctl
monitors=$(hyprctl monitors | grep '^Monitor.*:$' | cut -c9- | rev | cut -c9- | rev)
readarray -t monitor_list <<< "$monitors"
builtin_monitor="${monitor_list[0]}"
main_monitor="${monitor_list[1]}"
side_monitor="${monitor_list[2]}"

# Hyprland monitor template
template=$(cat <<EOF
-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

local builtinMonitor = "${builtin_monitor}"
local mainMonitor = "${main_monitor}"
local sideMonitor = "${side_monitor}"

hl.monitor({
    output = builtinMonitor,
    mode = "preferred",
    position = "auto-left",
    scale = 1,
})

hl.monitor({
    output = mainMonitor,
    mode = "preferred",
    position = "auto",
    scale = 1,
})

hl.monitor({
    output = sideMonitor,
    mode = "preferred",
    position = "auto-right",
    scale = 1,
})

hl.monitor({
    output = "",
    mode = "preferred",
    position = "auto",
    scale = 1,
})
EOF
)

filename="monitors-$(hostname).lua"

# Check if file exists
if [[ -e "$filename" && $FORCE -ne 1 ]]; then
  echo "Error: $filename already exists. Use -f to overwrite."
  exit 1
fi

# Write output
{
  echo "-- These monitors were found:"
  for monitor in "${monitor_list[@]}"; do
    echo "--   $monitor"
  done
  printf '%s\n' "$template"
} > "$filename"

echo "Monitor configuration written to $filename"
