--#####
-- sample hyprlock.conf
-- for more configuration options, refer https://wiki.hyprland.org/Hypr-Ecosystem/hyprlock
--
-- rendered text in all widgets supports pango markup (e.g. <b> or <i> tags)
-- ref. https://wiki.hyprland.org/Hypr-Ecosystem/hyprlock/#general-remarks
--
-- shortcuts to clear password buffer: ESC, Ctrl+U, Ctrl+Backspace
--
-- you can get started by copying this config to ~/.config/hypr/hyprlock.conf
--

-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

local font = "Monospace"

hl.curve("linear", { type = "bezier", points = { { 1, 1 }, { 0, 0 } } })
hl.animation({
    leaf = "fadeIn",
    enabled = true,
    speed = 5,
    bezier = "linear",
})
hl.animation({
    leaf = "fadeOut",
    enabled = true,
    speed = 5,
    bezier = "linear",
})
hl.animation({
    leaf = "inputFieldDots",
    enabled = true,
    speed = 2,
    bezier = "linear",
})

-- TODO: manual review — unknown section 'background {' on line 37

-- TODO: manual review — unknown section 'input-field {' on line 43
-- uncomment to use a letter instead of a dot to indicate the typed password
-- dots_text_format = *
-- dots_size = 0.4
-- uncomment to use an input indicator that does not show the password length (similar to swaylock's input indicator)
-- hide_input = true

-- TODO: manual review — unknown section 'label {' on line 75

-- TODO: manual review — unknown section 'label {' on line 87

-- TODO: manual review — unknown section 'label {' on line 98
hl.config({
    general = {
        hide_cursor = false,
    },
    -- uncomment to enable fingerprint authentication
    -- auth {
    --     fingerprint {
    --         enabled = true
    --         ready_message = Scan fingerprint to unlock
    --         present_message = Scanning...
    --         retry_delay = 250 # in milliseconds
    --     }
    -- }
    animations = {
        enabled = true,
    },
    -- TIME
    -- DATE
})

