-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

-- TODO: manual review — top-level key 'preload = ~/.config/hypr/wallpaper.png' has no enclosing section

--set the default wallpaper(s) seen on initial workspace(s) --depending on the number of monitors used
-- TODO: manual review — top-level key 'wallpaper = ,~/.config/hypr/wallpaper.png' has no enclosing section

--enable splash text rendering over the wallpaper
-- TODO: manual review — top-level key 'splash = false' has no enclosing section

--fully disable ipc
-- ipc = off

