-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

local builtinMonitor = "eDP-1"
local mainMonitor = "DP-5"
local sideMonitor = "DP-6"

hl.monitor({
    output = builtinMonitor,
    mode = "2880x1800@120",
    position = "auto-left",
    scale = 2,
})

hl.monitor({
    output = mainMonitor,
    mode = "1920x1080@60",
    position = "auto",
    scale = 1,
})

hl.monitor({
    output = sideMonitor,
    mode = "preferred",
    position = "auto-right",
    scale = 1.5,
})

hl.monitor({
    output = "",
    mode = preferred,
    position = "auto",
    scale = 1,
})
