-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

local mainMonitor = "DP-1"
local sideMonitor = "HDMI-A-1"
hl.monitor({
    output = mainMonitor,
    mode = "1920x1080@144",
    position = "0x0",
    scale = 1,
})

hl.monitor({
    output = sideMonitor,
    mode = "preferred",
    position = "auto-right",
    scale = 1.5,
})

hl.monitor({
    output = "",
    mode = "preferred",
    position = "auto",
    scale = 1,
})

