name: CI

on: [push]

jobs:
  Run_bootstrap_script:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Run script
        env:
          GIT_EMAIL: M@il.com
          GIT_NAME: ci_user
        run: |
          GIT_EMAIL=M@il.com GIT_NAME=ci_user ./bootstrap.sh
