name: CI

on: 
  push:
    paths-ignore: 
      - '**/*.md'

jobs:
  Run_bootstrap_script:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Run script
        env:
          GIT_EMAIL: M@il.com
          GIT_NAME: ci_user
        run: |
          GIT_EMAIL=M@il.com GIT_NAME=ci_user ./bootstrap.sh
          source ~/.bash_profile
          which zsh
      - name: Run zsh 
      # this launches a noop in zsh which should cause the .zshrc to be loaded and cause antigen to initially install all plugins
        run: |
          zsh -c "" 